# Linear Algebra Review and SciPy Basics

Screenshots from Section **2.2 Vectors and Matrices** in Biegler (2010)

**Recommended Links**
* [NumPy Documentation - Main Page](https://docs.scipy.org/doc/numpy-1.15.0/reference/)
* [SciPy Documentation - Main Page](https://docs.scipy.org/doc/scipy-1.1.0/reference/)
* [SciPy Linear Algebra - Tutorial](https://docs.scipy.org/doc/scipy-1.1.0/reference/tutorial/linalg.html)
* [SciPy Linear Algebra - API](https://docs.scipy.org/doc/scipy-1.1.0/reference/linalg.html)
* [SciPy Lecture Notes](http://www.scipy-lectures.org/) (Especially 1.1 - 1.6 for everyone and 2.1 - 2.2 for advanced users)

Tip: We will mostly use SciPy for linear algebra. (It has more sophisticated capabilities than NumPy.) We will use NumPy if/when SciPy does not offer a specific command.

In [1]:
# Load required Python libraries.
import numpy as np
from scipy import linalg

# Seed the random number generator so this notebook is reproducible
# (Pyomo style guide, section 8).
np.random.seed(0)

## Notation (for textbook)
* Scalar constants and variables - Greek letters
* Vectors - Lower case Roman letters
* Matrices - Upper case Roman letters

The notation for lectures will (hopefully) be obvious from context. I sometimes use Greek letters for constants and Roman letters for variables... unless the Greek letters have engineering or scientific meaning.

## Matrix Operations
![Matrix Operations](../../media/mat_op1.png)
![Matrix Operations](../../media/mat_op2.png)

In [2]:
# Generate random matrices
n = 2
m = 3

Ao = np.random.rand(n,m)
Bo = np.random.rand(m,n)

print("Ao = ")
print(Ao)
print("\nBo = ")
print(Bo)


# What is the dimension of A*B? Try to answer this without the computer.

# Calculate A*B using Python
print("\nAo*Bo =")
print(Ao.dot(Bo))

Ao = 
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]

Bo = 
[[0.43758721 0.891773  ]
 [0.96366276 0.38344152]
 [0.79172504 0.52889492]]

Ao*Bo =
[[1.40657799 1.08244885]
 [1.15806481 0.98996907]]


**Activity**
* Calculate $A_o^{T}$
* Create a square matrix and check if it is symmetric
* Create a 3x3 identity matrix

In [3]:
# Transpose
print("transpose(Ao) = \n",Ao.transpose(),"\n")

# Create a square matrix. Is it symmetric?

# Identify matrix
print("I = \n",np.identity(3),"\n")

transpose(Ao) = 
 [[0.5488135  0.54488318]
 [0.71518937 0.4236548 ]
 [0.60276338 0.64589411]] 

I = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



## Determinant
![Book](../../media/det.png)

In [4]:
# Generate random matrices
nd = 2

Ad = np.random.rand(nd,nd)
Bd = np.random.rand(nd,nd)

Cd = np.array([(1, 0, 0),(-2, 0, 0),(0, 1, 1)])

print("Ad = ")
print(Ad)
print("\nBd = ")
print(Bd)
print("\nCd = ")
print(Cd)

Ad = 
[[0.56804456 0.92559664]
 [0.07103606 0.0871293 ]]

Bd = 
[[0.0202184  0.83261985]
 [0.77815675 0.87001215]]

Cd = 
[[ 1  0  0]
 [-2  0  0]
 [ 0  1  1]]


**Activity**
* Verify the properties listed under *Some properties for the determinant include*
* Are $A_d$, $B_d$ or $C_d$ singular?

In [5]:
# Property 1
print("det(A*B) = ",linalg.det(Ad.dot(Bd)))

print("det(A)*det(B) = ",linalg.det(Ad)*linalg.det(Bd))

det(A*B) =  0.010247347495272154
det(A)*det(B) =  0.010247347495272162


In [6]:
# Property 2

In [7]:
# Property 3

In [8]:
# Property 4

**Another Example** (for at home)

Below is an example from *Linear Algebra and Its Applications* by David C. Lay, 3rd edition that shows how to calculate a determinant by hand.

![DET](../../media/det_ex1.png)
![DET](../../media/det_ex2.png)

## Rank
![Book](../../media/rank.png)

**Activity**
* Predict the rank of $A_o^T$, $B_o^T$, $A_d$, $B_d$, $C_d$
* Calculate np.linalg.matrix_rank(). Were you correct?

In [9]:
print("rank(A_o) = ",np.linalg.matrix_rank(Ao),"\n")

# Fill in remainder here.

rank(A_o) =  2 



## Inverse
![Book](../../media/inv.png)

**Activity**
1. Calculate the inverse of $A_o$ and verify that $A_o^{-1} A_o = I$
2. Verify that det($A^{-1}$) = 1/det($A$)
3. Is $Q$ an orthogonal matrix?

In [10]:
# Task 1

# Task 2

# Task 3
# Is this an orthogonal matrix? Yes, no, or need more information?
theta = 0.2
Q = np.array([(np.cos(theta), -np.sin(theta)),(np.sin(theta),np.cos(theta))])

print("Q = ")
print(Q)

Q = 
[[ 0.98006658 -0.19866933]
 [ 0.19866933  0.98006658]]


## Solving Linear Systems
Consider the linear system $A_l x = b_l$

In [11]:
Al = np.array([(4,3),(6,3)])
bl = np.array([1,0])
print("Al = \n",Al)
print("\nbl = \n",bl)

Al = 
 [[4 3]
 [6 3]]

bl = 
 [1 0]


### Explicit Inverse

Calculate $x$ by explicitly using $A_l^{-1}$. Hint: Use linalg.inv().

In [12]:
Ainv = linalg.inv(Al)
print("Ainv = \n",Ainv,"\n")

# Now calculate and print x

Ainv = 
 [[-0.5         0.5       ]
 [ 1.         -0.66666667]] 



### LU Decomposition

Perform LU decomposition on $A_l$. What structures do the $P$, $L$, and $U$ matrices have?

In [13]:
# Create test linear systems
A = np.random.rand(4,4)
print("A = \n",A,"\n")

b = np.random.rand(4,1)
print("b = \n",b,"\n")

A = 
 [[0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892]
 [0.52184832 0.41466194 0.26455561 0.77423369]
 [0.45615033 0.56843395 0.0187898  0.6176355 ]] 

b = 
 [[0.61209572]
 [0.616934  ]
 [0.94374808]
 [0.6818203 ]] 



In [14]:
# Perform LU decomposition
(P, L, U) = linalg.lu(A)

# Permutation matrix
print("P = \n",P)

# Lower triangular matrix
print("L = \n",L)

# Upper triangular matrix
print("U = \n",U)

# Verify result
print("P*L*U = \n",P.dot(L.dot(U)),"\n")

P = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
L = 
 [[ 1.          0.          0.          0.        ]
 [ 0.12085858  1.          0.          0.        ]
 [ 0.46611668  0.36061087  1.          0.        ]
 [ 0.53325009 -0.02114611 -0.08917973  1.        ]]
U = 
 [[ 0.97861834  0.79915856  0.46147936  0.78052918]
 [ 0.          0.54333585  0.08757955  0.85033527]
 [ 0.          0.         -0.22789556 -0.05282231]
 [ 0.          0.          0.          0.37128704]]
P*L*U = 
 [[0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892]
 [0.52184832 0.41466194 0.26455561 0.77423369]
 [0.45615033 0.56843395 0.0187898  0.6176355 ]] 



#### Is P orthogonal?

In [15]:
print("inv(P) = \n",linalg.inv(P),"\n")

print("transpose(P) = \n",P.T,"\n")

print("P.T*P = \n",np.matmul(P.T,P),"\n")

inv(P) = 
 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -0.  1.]
 [ 0.  0.  1. -0.]] 

transpose(P) = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]] 

P.T*P = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 



**Yes!** We see that $P^T = P^{-1}$ and $P^T \cdot P = I$.

#### MATLAB

Defines LU decomposition as follows:

$$ P \cdot A = L \cdot U$$

Consider $$A \cdot x=b$$

Using MATLAB LU definition

$$P\cdot A = L\cdot U$$
$$P^T \cdot P \cdot A = P^T \cdot L \cdot U$$
$$A = P^T \cdot L \cdot U$$

Substitute into linear system:

$$P^T \cdot L \cdot U \cdot x = b$$
$$ L \cdot U \cdot x = P \cdot b$$

Let $y = U \cdot x$ and substitute.

Step 1. Solve $L \cdot y = P \cdot b$ for $y$

Step 2. Solve $U \cdot x = y$ for $x$

In [16]:
Pb = P.dot(b)
print("P*b = ",Pb,"\n")

yLU = linalg.solve(L,Pb)
print("yLU = ",yLU,"\n")

xLU = linalg.solve(U,yLU)
print("xLU = ",xLU,"\n")

P*b =  [[0.61209572]
 [0.616934  ]
 [0.6818203 ]
 [0.94374808]] 

yLU =  [[0.61209572]
 [0.54295698]
 [0.20071609]
 [0.64672921]] 

xLU =  [[ 1.08292519]
 [-1.5197098 ]
 [-1.2844701 ]
 [ 1.74185778]] 



#### SciPy

Defines LU decomposition as:

$$ A = P \cdot L \cdot U $$

Consider $$A \cdot x=b$$

SciPy LU definition

$$A = P \cdot L\cdot U$$

Substitute into linear system:

$$P \cdot L \cdot U \cdot x = b$$
$$P^T \cdot P \cdot L \cdot U \cdot x = P^T \cdot b$$
$$L \cdot U \cdot x = P^T \cdot b$$

Let $y = U \cdot x$ and substitute.

Step 1. Solve $L \cdot y = P^T \cdot b$ for $y$

Step 2. Solve $U \cdot x = y$ for $x$

In [17]:
## LU decomposition algorithm.
Pb = (P.T).dot(b)
print("P.T*b = ",Pb,"\n")

yLU = linalg.solve(L,Pb)
print("yLU = ",yLU,"\n")

xLU = linalg.solve(U,yLU)
print("xLU = ",xLU,"\n")

P.T*b =  [[0.61209572]
 [0.616934  ]
 [0.6818203 ]
 [0.94374808]] 

yLU =  [[0.61209572]
 [0.54295698]
 [0.20071609]
 [0.64672921]] 

xLU =  [[ 1.08292519]
 [-1.5197098 ]
 [-1.2844701 ]
 [ 1.74185778]] 



**What is the difference?** A transpose.


#### Verify our answer with `linalg.solve`

Solve the linear system using linalg.solve

In [18]:
x = linalg.solve(Al,bl)
print("x = \n",x)

x = 
 [-0.5  1. ]


## Invertible Matrix Theorem
Screenshots from *Linear Algebra and Its Applications* by David C. Lay, 3rd edition

![IMT](../../media/imt1.png)
![IMT](../../media/imt2.png)
![IMT](../../media/imt3.png)
![IMT](../../media/imt4.png)

## Eigenvectors and Eigenvalues
![Book](../../media/eig.png)

### Level sets of a quadratic form, as one picture

![Level sets of the quadratic form $q(x)=\tfrac12 x^\mathsf{T} A x$ for symmetric positive definite $A$, with the eigenvectors drawn as the principal axes. Both panels use the same eigenvectors and the same level $q=2$; only the eigenvalues change.](../../media/figures/quadratic-form-level-sets.png)

Eigenvalues and eigenvectors of a **symmetric** matrix have a picture: they are the principal
axes of the level sets of $q(x) = \tfrac12 x^\mathsf{T} A x$. In the rotated coordinates
$z = V^\mathsf{T} x$ the level set is $\lambda_1 z_1^2 + \lambda_2 z_2^2 = 2q$, so the
semi-axis along $v_i$ has length $\sqrt{2q/\lambda_i} \propto 1/\sqrt{\lambda_i}$ --- a
large eigenvalue means *steep*, hence *short*.

The right-hand panel is the same picture with a condition number of 100. Note the axis ratio
is $\sqrt{\kappa(A)}$, not $\kappa(A)$; by the time you reach the $\kappa \approx 10^{14}$
you will meet in the **Condition Number** section below, the ellipse is not drawable.

This figure is rendered from `figures/plots/quadratic-form-level-sets.py` and is the **same
image printed in the course pack**, so what you annotate in lecture and what you see here
cannot drift apart. The cells below are the live version.


In [19]:
Ae = np.array([(0, -4, -6), (-1, 0, -3), (1, 2, 5)])
print("Ae = \n",Ae)

Ae = 
 [[ 0 -4 -6]
 [-1  0 -3]
 [ 1  2  5]]


**Activity**
* Do you expect this matrix to have negative eigenvalues? Choose: Yes / No / Cannot tell from inspection.
* Calculate the eigenvalues.
* Based on your calculations above, is this matrix i) positive definite, ii) positive semi definite, iii) negative definite, iv) negative semi definite, v) indefinite, or vi) cannot say without additional calculations? Write a sentence to justify your answer.
* Calculate the determinant using only the eigenvalues.

In [20]:
# Expect negative eigenvalues?
# Yes / No / Cannot tell from inspection?
# Write a sentence to justify your answer.

### Calculate eigenvalues

# Matrix Al
print("Matrix = \n",Al,"\n")
l, v = linalg.eig(Al)
print("Eigenvalues = ",l,"\n")
print("Eigenvectors = \n",v,"\n")

Matrix = 
 [[4 3]
 [6 3]] 

Eigenvalues =  [ 7.77200187+0.j -0.77200187+0.j] 

Eigenvectors = 
 [[ 0.62246561 -0.53222953]
 [ 0.78264715  0.8466001 ]] 



## Singular Value Decomposition
Notes will be given in class.

**Activity**
* Calculate singular value decomposition of $A_l$ and $C_d$
* What is the rank of each matrix?

In [21]:
# Matrix Al
print("Matrix = \n",Al,"\n")
U,s,Vh = linalg.svd(Al)
print("U = \n",U,"\n")
print("S = \n",s,"\n")
print("Vh = \n",Vh,"\n")

## Rank (from inspecting singular values)?

Matrix = 
 [[4 3]
 [6 3]] 

U = 
 [[-0.59581566 -0.80312122]
 [-0.80312122  0.59581566]] 

S = 
 [8.33557912 0.71980602] 

Vh = 
 [[-0.86400595 -0.50348159]
 [ 0.50348159 -0.86400595]] 



## Vector and Matrix Norms
![Book](../../media/norm1.png)
![Book](../../media/norm2.png)

In [22]:
x = np.random.rand(3,1)
print("x = \n",x)

y = np.random.rand(3,1)
print("y = \n",y)

x = 
 [[0.3595079 ]
 [0.43703195]
 [0.6976312 ]]
y = 
 [[0.06022547]
 [0.66676672]
 [0.67063787]]


**Activity**
* Verify the vector norm properties hold for the p-2 norm using $x$ and $y$. Hint: linalg.norm()
* Calculate $||A_l||_1$, $||A_l||_{\infty}$ and $||A_l||_2$ using both the rules given above and SciPy

## Condition Number

**Activity**
* Estimate the condition number of $A_l$ by inspecting the SVD results.
* Calculate the condition number of $A_l$ using np.linalg.cond()